In [1]:
import random
import agent as agent
from env import *
import scipy.special
import time

Parameters

In [22]:
maximum_depth=3
num_of_Mu_chunks=1

Make an instance of tiger porblem environment

In [23]:
e=tiger_POMDP_env(read_config=True,config_address='./tiger.json',parameters=None)

make an instance of Bauerle and Rieder agent

In [24]:
ag=agent.Bauerle_Rieder_agent(environment=e, num_of_Mu_chunks=num_of_Mu_chunks,max_iterations=maximum_depth)

In [25]:
# generate_possible_wealths(np.unique(self.env.rewards),self.initial_wealth,self.env.discount_factor,self.max_time_step)

wlth = ag.generate_possible_wealths(np.unique(e.rewards),0,1,maximum_depth)
print("RWRD",np.unique(e.rewards))
print("WLTH",wlth,len(wlth))
chunk = ag.chunk_mu([0,1],wlth,num_of_Mu_chunks)
print("CHUNK",chunk,chunk.shape)
len(chunk)

RWRD [-2.  -1.  -0.5  1.   2. ]
WLTH [-6.  -5.  -4.5 -4.  -3.5 -3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.
  1.5  2.   2.5  3.   3.5  4.   5.   6. ] 22
CHUNK [[1 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]] (44, 44)


44

In [26]:
start = time.time()
ag.pre_planning_paration(make_and_save_Mu=True,save_Mu2index_chunks=True)
end = time.time()
print("Took:",np.round(end-start,2))


Took: 2.65


In [27]:
xa = ag.value_iteration(utility_function='risk-neutral')

step: 3
==== iterations
Self.S [-5.6  -4.7  -4.6  -4.25 -4.1  -3.8  -3.7  -3.7  -3.6  -3.35 -3.25 -3.2
 -3.2  -2.9  -2.9  -2.8  -2.75 -2.7  -2.6  -2.45 -2.35 -2.3  -2.25 -2.
 -2.   -1.9  -1.85 -1.85 -1.8  -1.7  -1.6  -1.55 -1.55 -1.45 -1.4  -1.35
 -1.25 -1.1  -1.1  -1.   -1.   -1.   -0.95 -0.9  -0.8  -0.7  -0.7  -0.65
 -0.65 -0.55 -0.55 -0.5  -0.5  -0.5  -0.45 -0.35 -0.35 -0.25 -0.25 -0.2
 -0.2  -0.1  -0.1  -0.05 -0.05  0.    0.1   0.1   0.1   0.2   0.2   0.35
  0.35  0.4   0.4   0.45  0.55  0.65  0.65  0.7   0.7   0.8   0.85  0.9
  1.    1.    1.    1.1   1.1   1.3   1.35  1.45  1.45  1.55  1.6   1.7
  1.8   1.9   2.    2.    2.2   2.35  2.35  2.45  2.45  2.6   2.7   2.8
  2.9   2.9   3.1   3.35  3.35  3.6   3.7   3.7   3.8   4.6   4.7   5.6 ]
step: 2
(5, 72)
a: 0
int_mus [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] possible [-3.8  -2.9  -2.8  -2.45 -2.3  -2.   -1.9  -1.8  -1.45 -1.4  -1.1  -1.
 -0.95 -0.9  -0.

ValueError: shape mismatch: value array of shape (72,36) could not be broadcast to indexing result of shape (0,72)

In [11]:
#Size of MU
start = time.time()
sum = 0
for i in range(1,5):
        sum += scipy.special.binom(44, i)
print(sum)
e.observations

149985.0


{0: 'sound_right', 1: 'soud_left'}

In [12]:
hashset = {}
for i in range(chunk.shape[0]):
    hashset[hash(str(chunk[i,:]))] = 0
len(hashset.keys())

12

In [11]:
np.append(([1,2],2),3)

array([list([1, 2]), 2, 3], dtype=object)

In [12]:
e.observation_matrix

array([[[0.89, 0.11],
        [0.12, 0.88]],

       [[0.8 , 0.2 ],
        [0.2 , 0.8 ]],

       [[0.8 , 0.2 ],
        [0.2 , 0.8 ]],

       [[0.8 , 0.2 ],
        [0.2 , 0.8 ]],

       [[0.8 , 0.2 ],
        [0.2 , 0.8 ]]])

In [13]:
e.transition_matrix

array([[[0.8 , 0.2 ],
        [0.5 , 0.5 ],
        [0.5 , 0.5 ],
        [0.5 , 0.5 ],
        [0.5 , 0.5 ]],

       [[0.15, 0.85],
        [0.5 , 0.5 ],
        [0.5 , 0.5 ],
        [0.5 , 0.5 ],
        [0.5 , 0.5 ]]])

2.value-iteration<br>
<br>
Its result are in value_function, action_function, and step_indexes attributes

In [14]:
#Self.S [-2.  -1.  -0.5  0.   1.   2. ]

In [64]:
ag.value_function[-1][332]

-0.5

In [16]:
ag.action_function

[array([None, None, None, None, None, None, None, None, None, None, None,
        None, None, None, None, None, None, None, None, 3, None, None,
        None, None, None, None, None, None, None, None, None, None, None,
        None, None, None, None, None, None, None, None, None, None, None,
        None, None, None, None, None, None, None, None, None, None, None,
        4, None, None, None, None, None, None, None, None, None, None,
        None, None, None, None, None, None], dtype=object),
 array([None, None, None, None, None, 3, None, None, None, None, None, 3,
        None, None, None, 3, None, None, None, 3, None, None, None, None,
        None, None, 3, None, None, None, None, None, 3, None, None, None,
        None, None, None, None, None, 4, None, None, None, None, None, 4,
        None, None, None, 4, None, None, None, 4, None, None, None, None,
        None, None, 4, None, None, None, None, None, 4, None, None, None],
       dtype=object),
 None]

In [17]:
e.observation_matrix

array([[[0.89, 0.11],
        [0.12, 0.88]],

       [[0.8 , 0.2 ],
        [0.2 , 0.8 ]],

       [[0.8 , 0.2 ],
        [0.2 , 0.8 ]],

       [[0.8 , 0.2 ],
        [0.2 , 0.8 ]],

       [[0.8 , 0.2 ],
        [0.2 , 0.8 ]]])

In [18]:
xa[:,:,:]
BEST [2. 2.] [3 4]
XA_vals [[[-0.5 -0.5]
  [ 1.  -1. ]
  [-1.   1. ]
  [ 2.  -2. ]
  [-2.   2. ]]

 [[-0.5 -0.5]
  [ 1.  -1. ]
  [-1.   1. ]
  [ 2.  -2. ]
  [-2.   2. ]]] (2, 5, 2)

SyntaxError: invalid syntax (<ipython-input-18-0e0510a842a6>, line 2)

==========

<b>Simulation

After using value iteration, we have computed anything. So, we need to update our agent beliefs by interacting with environment.<br>
We have two essential functions here: do_action() and update_agent() 

An experiment with depth 2 and 3 chunk points

In [21]:
get_possible_s = lambda step : ag.generate_possible_wealths(np.unique(ag.env.rewards),ag.initial_wealth,ag.env.discount_factor,step)

num_to_act=dict(zip(list(e.actions.values()),list(e.actions.keys())))

# reset the agent with random starting x and probability of P(y=0 and s=0)=1/3 and P(y=1 and s=0)=2/3
init_observation = random.randint(0,1)
print("Initial Observation:",init_observation)
ag.reset(initiative_observation=init_observation)


max_s = list(get_possible_s(maximum_depth))*2
acc_reward = 0

for t in range(maximum_depth):
    action,value,belief=ag.do_action()   
    print("Step: {} Action: {} Value: {} Belief: {} State: {} ".format(ag.current_internal_timeStep,action,value,np.argmax(belief),e.current_state),end="")
    t1,t2,new_state,last_reward,new_observation=e.step(num_to_act[action])
    print("Reward {}".format(last_reward))
    
    acc_reward += last_reward
    
    ag.update_agent(new_observation)

    print('Step: {} New State: {} New Observation: {} New Belief {}'.format(ag.current_internal_timeStep,e.current_state,new_observation,np.argmax(ag.current_internal_belief)))
    print(ag.current_internal_belief)

print("Actual Reward {}, Beliefed Reward: {}".format(acc_reward,max_s[np.argmax(ag.current_internal_belief)]))

    
    

Initial Observation: 0
Step: 0 Action: 3 Value: 2.5999999999999996 Belief: 19 State: 1 Reward -2.0
int [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 24  0  0  0]]
Step: 1 New State: 1 New Observation: 1 New Belief 68
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0]]
Step: 1 Action: 4 Value: 2.5999999999999996 Belief: 68 State: 1 Reward 2.0
int [[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  8  0  0
   0  0  0  0  0  0  0  0  0  0  0 16  0  0  0  0  0  0  0  0  0  0  0  0
   0  0  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0  0  0  0  4]]
Step: 2 New State: 1 New Observation: 0 New Belief 35
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [35]:
#[0 0 0 2 0 0 0 0 0 1 0 0]
belief=[0., 0., 0., 0., 0., 0., 0., 0., 0., 3., 0., 0.]
step = 0

print('Possible S',get_possible_s(step))

result=ag.say_calculator(x=0,
                           action=0,
                           x_prim=0,
                           current_int_mu=np.array([belief]),
                           z=np.power(ag.env.gamma,step),
                           current_possible_s=get_possible_s(step))
print(result)

Possible S [0]
[[0 0 2 0 0 0 0 0 1 0 0 0]]


In [213]:
ag.value_function

[array([None, None, None, 2.0, None, None, None, None, None, 2.0, None,
        None], dtype=object),
 array([-2. , -1. , -0.5,  0. ,  1. ,  2. , -2. , -1. , -0.5,  0. ,  1. ,
         2. ])]

In [58]:
print('Possible S',get_possible_s(2))

Possible S [-3.8  -2.9  -2.8  -2.45 -2.3  -2.   -1.9  -1.8  -1.45 -1.4  -1.1  -1.
 -0.95 -0.9  -0.8  -0.5  -0.45 -0.2  -0.1   0.    0.1   0.2   0.4   0.55
  0.8   0.9   1.    1.1   1.3   1.55  1.8   1.9   2.    2.8   2.9   3.8 ]


In [18]:
ag.num_of_PDF_chunks

1

In [57]:
random.randint(0,1)

1

In [18]:
ag.nearest_grid_points(np.array([[ 0 , 0 ,10 , 0,  0  ,0,  0 , 0, 20 , 0 , 0 , 0]]))

array([[ 0,  0, 10,  0,  0,  0,  0,  0, 20,  0,  0,  0]])